version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "1337:1337"
    environment:
      - SPRING_PROFILES_ACTIVE=sqlite

  frontend:
    build: ./frontend
    ports:
      - "31337:80"
    depends_on:
      - backend