version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "1337:1337"
    env_file:
      - .env

  frontend:
    build: ./frontend
    ports:
      - "31337:80"
    depends_on:
      - backend