
server.port=1337
spring.application.name=Wespresso World

# API version and base URL
server.servlet.context-path=/api/v1

# 1. Enable the H2 Console (The Web Interface)
spring.h2.console.enabled=true

# 2. Set the "Address" of your database
spring.datasource.url=jdbc:h2:mem:wespresso_db

# 3. Credentials (You'll use these to log in)
spring.datasource.username=sa
spring.datasource.password=password

# 4. Show the SQL in the terminal (Great for learning!)
spring.jpa.show-sql=true

# 5. Fixes a common "Console not found" error
spring.h2.console.path=/h2-console