server.port=1337
spring.application.name=Wespresso World
server.servlet.context-path=/api/v1

# Set active profile (switch between h2 and sqlite)
spring.profiles.active=sqlite

# Show the SQL in the terminal
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# logging
logging.level.org.springframework.security=DEBUG

# JWT Key Info
jwt.secret=${JWT_SECRET:wespresso-super-secret-key-2026-ctf-challenge}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Multipart upload limits
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Vulnerabilities switches
vuln.jwt-none.enabled=${ENV_VULN_JWT_NONE_ENABLED:true}
vuln.ssti-thymeleaf.enabled=${VULN_SSTI_THYMELEAF_ENABLED:false}

# Prevent FreeMarker from trying to handle Thymeleaf's routes
spring.freemarker.check-template-location=false